# Data Volume Container
dbdata:
  image: mongo
  entrypoint: /bin/bash
  volumes:
   - /mongodata:/data/db
# DB Container
db:
  image: mongo
  expose:
    - 27017
  command: --smallfiles
  volumes_from:
    - dbdata     
# Python App
web:
  build: . 
  ports:
    - "5000:5000" 
  links:
   - db:db
